worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # Definição do servidor
    server {
        listen       80;
        server_name  localhost;

        # Localização dos arquivos estáticos (ajustar conforme necessário)
        location / {
            root   /var/www/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Configuração do PHP-FPM
        location ~ \.php$ {
            fastcgi_pass   php-fpm:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # Configuração para lidar com arquivos .ht
        location ~ /\.ht {
            deny  all;
        }
    }
}
